### PR TITLE
.toml parsing bug

### PR DESCRIPTION
**Pull request by tjknoth**
* bump version of `slm-toml` dependency (this contains the actual parser fix)
* use `parse-file` API instead of `parse-string` -- this ensures that parser error messages will contain the actual file name (instead of the opaque `<input>:line:col` we see right now)
* rename `parse-slm-toml` to `parse-slm-toml-file` to clarify the fact that the string input is a filepath
* bump version

This depends on an `slm-toml` PR and release, will not merge until that gets in.

jitx ticket: PROD-213

### CODE REVIEW

**Comment by callendorph** [comment]
There is no `v.4.4.0` tag for the `slm-toml` dependency - this causes the build to fail locally for me.

**Review by callendorph — APPROVED** [review]
Looks good :+1: 
Thanks for the file handling cleanup that makes things much more readable.

We need to add the tag on `slm-toml` and that should be good to go.

CI build fails on `libcurl` and I'm not sure what that is about. I'm able to successfully download it locally but I'm on a mac so it may be different. @jwatson0  - thoughts?

**Comment by tjknoth** [comment]
> There is no `v0.4.4` tag for the `slm-toml` dependency - this causes the build to fail locally for me.

forgot to `publish`, nice catch. Should work now.

**Comment by jwatson0** [comment]
I fixed the libcurl thing. There was an extra version of libcurl on artifactory that didn't include all necessary builds, so I removed it.  I also merged changes to the master branch, so I merged those to this PR.

**Pull request merged**
